<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTm0Cjxt\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTm0Cjxt/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerTm0Cjxt.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerTm0Cjxt\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerTm0Cjxt\appAppKernelProdContainer([
    'container.build_hash' => 'Tm0Cjxt',
    'container.build_id' => 'b9a8a776',
    'container.build_time' => 1716841662,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTm0Cjxt');
