<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDXve5vO\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDXve5vO/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDXve5vO.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDXve5vO\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDXve5vO\appAppKernelProdContainer([
    'container.build_hash' => 'DXve5vO',
    'container.build_id' => '2bef80d6',
    'container.build_time' => 1716237513,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDXve5vO');
