<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0hTRe2f\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0hTRe2f/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container0hTRe2f.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container0hTRe2f\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container0hTRe2f\appAppKernelProdContainer([
    'container.build_hash' => '0hTRe2f',
    'container.build_id' => '2d5923d5',
    'container.build_time' => 1716840100,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0hTRe2f');
